name: frontend_mobile
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.5
  flutter_bloc: ^8.1.3

  # GraphQL
  graphql_flutter: ^5.1.0
  http: ^1.1.0

  # Firebase
  firebase_core: ^3.9.1
  firebase_auth: ^5.6.2      
  cloud_firestore: ^5.6.11
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.4

  # Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - docs/png/google.png

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/dancingscript/DancingScript-Regular.ttf
        - asset: assets/fonts/dancingscript/DancingScript-Bold.ttf
          weight: 700
