// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpDFkE0ZgM1VtFCn3ZCRLnwSUeAIeJ0G8',
    appId: '1:425980769579:web:27066750e61dfe9bf3816e',
    messagingSenderId: '425980769579',
    projectId: 'mynotes-8d8e9',
    authDomain: 'mynotes-8d8e9.firebaseapp.com',
    storageBucket: 'mynotes-8d8e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpDFkE0ZgM1VtFCn3ZCRLnwSUeAIeJ0G8',
    appId: '1:425980769579:android:27066750e61dfe9bf3816e',
    messagingSenderId: '425980769579',
    projectId: 'mynotes-8d8e9',
    authDomain: 'mynotes-8d8e9.firebaseapp.com',
    storageBucket: 'mynotes-8d8e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDFkE0ZgM1VtFCn3ZCRLnwSUeAIeJ0G8',
    appId: '1:425980769579:ios:27066750e61dfe9bf3816e',
    messagingSenderId: '425980769579',
    projectId: 'mynotes-8d8e9',
    authDomain: 'mynotes-8d8e9.firebaseapp.com',
    storageBucket: 'mynotes-8d8e9.firebasestorage.app',
    iosBundleId: 'com.company.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpDFkE0ZgM1VtFCn3ZCRLnwSUeAIeJ0G8',
    appId: '1:425980769579:macos:27066750e61dfe9bf3816e',
    messagingSenderId: '425980769579',
    projectId: 'mynotes-8d8e9',
    authDomain: 'mynotes-8d8e9.firebaseapp.com',
    storageBucket: 'mynotes-8d8e9.firebasestorage.app',
    iosBundleId: 'com.company.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpDFkE0ZgM1VtFCn3ZCRLnwSUeAIeJ0G8',
    appId: '1:425980769579:windows:27066750e61dfe9bf3816e',
    messagingSenderId: '425980769579',
    projectId: 'mynotes-8d8e9',
    authDomain: 'mynotes-8d8e9.firebaseapp.com',
    storageBucket: 'mynotes-8d8e9.firebasestorage.app',
  );
}
